
@baseURL = http://localhost:4000/api
@username = "mrtec6"
@password = "12abcd"

###
# @name postLogin
POST {{baseURL}}/signup
content-type: application/json

{
    "username":"Hitech",
    "password":"12abcd",
    "code":1234,
    "image":"mm284775858"
   
}



###GET ME
@access_Token = {{postLogin.response.body.accessToken}}
GET {{baseURL}}/profile
Accept: application/json
Authorization: Bearer {{access_Token}}


# DELETE  http://localhost:3000/api/delete/5
