
@baseURL = http://localhost:3000/api/login


POST {{baseURL}}/login
content-type: application/json
Authorization: 

{
    "username":"mrtec6",
    "password":"12abcd"
   
}
### Login

GET {{baseURL}}/login

###
GET {{baseURL}}/users


# DELETE  http://localhost:3000/api/delete/5
